Repository Ultimaker/Cura, pull requests merged in 2018-05, with the labels that each got.

#3477 Added retraction_combing_max_distance setting
  resources/definitions/fdmprinter.def.json
Labels: Status: In Progress

#3599 Fixes for cura on ARM/Mali-based systems
  cura_app.py
  plugins/SimulationView/layers.shader
  plugins/SimulationView/layers_shadow.shader
  plugins/SimulationView/simulationview_composite.shader
  plugins/XRayView/xray_composite.shader
  resources/shaders/grid.shader
  resources/shaders/striped.shader
Labels: Platform: Linux, Status: In Progress, Type: Bug

#3762 PP formula based temperature fixes S5
  resources/definitions/ultimaker_s5.def.json
  resources/quality/ultimaker_s5/um_s5_aa0.25_PP_Normal_Quality.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_ABS_Draft_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_ABS_Fast_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_ABS_High_Quality.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_ABS_Normal_Quality.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_CPE_Draft_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_CPE_Fast_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_CPE_High_Quality.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_CPE_Normal_Quality.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_PP_Draft_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_PP_Fast_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_PP_Normal_Quality.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_TPU_Draft_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_TPU_Fast_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.4_TPU_Normal_Quality.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.8_PLA_Draft_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.8_PLA_Superdraft_Print.inst.cfg
  resources/quality/ultimaker_s5/um_s5_aa0.8_PLA_Verydraft_Print.inst.cfg
Labels: Status: In Progress, Type: Improvement

#3412 support_wall_count setting
  resources/definitions/fdmprinter.def.json
Labels: Status: In Progress

#3690 Fix some typo and wrong translation.
  resources/i18n/ko_KR/cura.po
  resources/i18n/ko_KR/fdmprinter.def.json.po
Labels: Type: Bug

#3848 Select models after loading
  cura/CuraApplication.py
  resources/qml/Preferences/GeneralPage.qml
Labels: Category: Cura, Status: In Progress, Type: New Feature

#3786 Backup Manager and API
  .gitignore
  cura/API/Backups.py
  cura/API/__init__.py
  cura/AutoSave.py
  cura/Backups/Backup.py
  cura/Backups/BackupsManager.py
  cura/CuraApplication.py
  cura/Stages/CuraStage.py
  plugins/AutoSave/__init__.py
  plugins/AutoSave/plugin.json
  plugins/Toolbox/src/Toolbox.py
  plugins/USBPrinting/USBPrinterOutputDeviceManager.py
Labels: Status: In Progress

#3593 Separate qml files for Prepare and Monitor stages
  plugins/MonitorStage/MonitorStage.py
  plugins/PrepareStage/PrepareStage.py
  resources/qml/MonitorButton.qml
  resources/qml/MonitorSidebar.qml
  resources/qml/PrepareSidebar.qml
  resources/qml/SidebarHeader.qml
Labels: Status: In Progress, Type: Improvement

#3597 [3.3] Fix getting multiple extruder temperatures from USB printer
  plugins/USBPrinting/USBPrinterOutputDevice.py
Labels: Status: In Progress

#3648 Bug fixes and improvements for PauseAtHeight plugin
  plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
Labels: Status: In Progress

#3691 Only open USB ports if the printer understands gcode.
  plugins/USBPrinting/USBPrinterOutputDeviceManager.py
Labels: Category: Cura, Status: In Progress, Type: Bug

#3413 settings for infill support
  plugins/VersionUpgrade/VersionUpgrade33to34/VersionUpgrade33to34.py
  resources/definitions/fdmprinter.def.json
Labels: Status: In Progress

#3479 Added wall_min_flow and wall_min_flow_retract settings.
  resources/definitions/fdmprinter.def.json
Labels: Status: In Progress
