Repository Ultimaker/Cura, pull requests merged in 2018-04, with the labels that each got.

#3617 Add setting to try multiple line thicknesses
  resources/definitions/fdmprinter.def.json
Labels: Status: In Progress

#3411 setting to disable omitting retractions in support
  resources/definitions/fdmprinter.def.json
Labels: Status: In Progress

#3651 No! G90 does not command absolute extrusion, M82 does that.
  plugins/GCodeReader/RepRapFlavorParser.py
Labels: Status: In Progress

#3675 PC profile adjustment
  resources/quality/ultimaker3/um3_aa0.4_PC_Draft_Print.inst.cfg
  resources/quality/ultimaker3/um3_aa0.4_PC_Fast_Print.inst.cfg
  resources/quality/ultimaker3/um3_aa0.4_PC_High_Quality.inst.cfg
  resources/quality/ultimaker3/um3_aa0.4_PC_Normal_Quality.inst.cfg
Labels: Status: In Progress

#3620 [3.3] Prevent preheat timeout from occurring during a print
  cura/PrinterOutput/GenericOutputController.py
  plugins/USBPrinting/USBPrinterOutputDevice.py
Labels: Category: Cura, Status: In Progress

#3545 [3.3] Support Eraser related fixes
  cura/MultiplyObjectsJob.py
  cura/Scene/CuraSceneNode.py
  plugins/SupportEraser/SupportEraser.py
Labels: Status: In Progress

#3584 Add ZYYX Agile printer.
  resources/definitions/zyyx_agile.def.json
  resources/meshes/zyyx_platform.stl
  resources/quality/zyyx/zyyx_agile_global_fast.inst.cfg
  resources/quality/zyyx/zyyx_agile_global_fine.inst.cfg
  resources/quality/zyyx/zyyx_agile_global_normal.inst.cfg
  resources/quality/zyyx/zyyx_agile_pro_flex_fast.inst.cfg
  resources/quality/zyyx/zyyx_agile_pro_flex_fine.inst.cfg
  resources/quality/zyyx/zyyx_agile_pro_flex_normal.inst.cfg
  resources/quality/zyyx/zyyx_agile_pro_pla_fast.inst.cfg
  resources/quality/zyyx/zyyx_agile_pro_pla_fine.inst.cfg
  resources/quality/zyyx/zyyx_agile_pro_pla_normal.inst.cfg
Labels: Status: In Progress

#3642 Printer Definitions for Rigid3D Mucit
  resources/definitions/rigid3d_mucit.def.json
  resources/meshes/rigid3d_mucit_platform.stl
Labels: Category: Cura, Status: In Progress

#3666 Show information dialogue on what usage data is sent
  cura/CuraApplication.py
  plugins/SliceInfoPlugin/MoreInfoWindow.qml
  plugins/SliceInfoPlugin/SliceInfo.py
  plugins/SliceInfoPlugin/example_data.json
  resources/qml/Preferences/GeneralPage.qml
Labels: Status: In Progress

#3688 Felix profile
  resources/definitions/felixtec4dual.def.json
  resources/extruders/felixtec4_dual_extruder_0.def.json
  resources/extruders/felixtec4_dual_extruder_1.def.json
  resources/meshes/FelixTec4_platform.stl
  resources/variants/felixtec4_0.25.inst.cfg
  resources/variants/felixtec4_0.35.inst.cfg
  resources/variants/felixtec4_0.50.inst.cfg
  resources/variants/felixtec4_0.70.inst.cfg
Labels: Category: Cura, Status: In Progress

#3638 Fix a crash when a variant has no hardware_type
  cura/Machines/VariantManager.py
Labels: Type: Bug
