Repository Ultimaker/Cura, pull requests merged in 2019-12, with the labels that each got.

#5335 PostProcessingPlugin Script for 2-1 Dual Extruders - ColorMix 2-1
  plugins/PostProcessingPlugin/scripts/ColorMix.py
Labels: Status: In Progress

#6694 HMS434 update
  resources/definitions/hms434.def.json
  resources/extruders/hms434_tool_1.def.json
  resources/extruders/hms434_tool_2.def.json
Labels: Category: 3rd-Party, Category: Settings

#6831 Hopefully Adding the Anet 3d Printer files to the latest version
  resources/definitions/anet3d.def.json
  resources/definitions/anet3d_a2 plus.def.json
  resources/definitions/anet3d_a2.def.json
  resources/definitions/anet3d_a6.def.json
  resources/definitions/anet3d_a8 plus.def.json
  resources/definitions/anet3d_a8.def.json
  resources/definitions/anet3d_e10.def.json
  resources/definitions/anet3d_e12.def.json
  resources/definitions/anet3d_e16.def.json
  resources/definitions/anet3d_et4 pro.def.json
  resources/definitions/anet3d_et4 x.def.json
  resources/definitions/anet3d_et4.def.json
  resources/definitions/anet3d_et5 x.def.json
  resources/definitions/anet3d_et5.def.json
  resources/definitions/anet_a6.def.json
  resources/extruders/anet3d_extruder_0.def.json
Labels: Category: 3rd-Party, Category: Settings

#6845 CURA-7038/Show list of packages to be synced
  plugins/Toolbox/resources/qml/dialogs/CompatibilityDialog.qml
  plugins/Toolbox/src/SubscribedPackagesModel.py
  plugins/Toolbox/src/Toolbox.py
Labels: Category: Cloud, Category: Cura, Type: New Feature
