Repository Ultimaker/Cura, pull requests merged in 2023-01, with the labels that each got.

#13630 Use ARGV0 to select the executable to execute from AppRun. Intended to run CuraEngine
  packaging/AppImage/AppRun
Labels: PR: Community Contribution :crown:

#12796 Flsun V400
  resources/definitions/flsun_v400.def.json
  resources/extruders/flsun_v400_extruder_0.def.json
  resources/meshes/flsun_v400.stl
  resources/quality/flsun_v400/flsun_v400_normal.inst.cfg
Labels: PR: Printer Definitions ⚙️, PR: Community Contribution :crown:

#14231 Add Elegoo Neptune series Printer Configuration.
  resources/definitions/elegoo_base.def.json
  resources/definitions/elegoo_neptune_1.def.json
  resources/definitions/elegoo_neptune_2s.def.json
  resources/definitions/elegoo_neptune_3.def.json
  resources/definitions/elegoo_neptune_3max.def.json
  resources/definitions/elegoo_neptune_3plus.def.json
  resources/definitions/elegoo_neptune_3pro.def.json
  resources/definitions/elegoo_neptune_x.def.json
  resources/extruders/elegoo_extruder_0.def.json
  resources/meshes/elegoo_platform.3mf
  resources/meshes/elegoo_platform_max.3mf
  resources/quality/elegoo/base/abs040/abs_040012.inst.cfg
  resources/quality/elegoo/base/abs040/abs_040016.inst.cfg
  resources/quality/elegoo/base/abs040/abs_040020.inst.cfg
  resources/quality/elegoo/base/abs040/abs_040024.inst.cfg
  resources/quality/elegoo/base/abs040/abs_040028.inst.cfg
  resources/quality/elegoo/base/asa040/asa_040012.inst.cfg
  resources/quality/elegoo/base/asa040/asa_040016.inst.cfg
  resources/quality/elegoo/base/asa040/asa_040020.inst.cfg
  resources/quality/elegoo/base/asa040/asa_040024.inst.cfg
  resources/quality/elegoo/base/asa040/asa_040028.inst.cfg
  resources/quality/elegoo/base/elegoo_global_012_high.inst.cfg
  resources/quality/elegoo/base/elegoo_global_016_normal.inst.cfg
  resources/quality/elegoo/base/elegoo_global_020_fine.inst.cfg
  resources/quality/elegoo/base/elegoo_global_024_medium.inst.cfg
  resources/quality/elegoo/base/elegoo_global_028_draft.inst.cfg
  resources/quality/elegoo/base/petg040/petg_040012.inst.cfg
  resources/quality/elegoo/base/petg040/petg_040016.inst.cfg
  resources/quality/elegoo/base/petg040/petg_040020.inst.cfg
  resources/quality/elegoo/base/petg040/petg_040024.inst.cfg
  resources/quality/elegoo/base/petg040/petg_040028.inst.cfg
  resources/quality/elegoo/base/pla040/pla_040012.inst.cfg
  resources/quality/elegoo/base/pla040/pla_040016.inst.cfg
  resources/quality/elegoo/base/pla040/pla_040020.inst.cfg
  resources/quality/elegoo/base/pla040/pla_040024.inst.cfg
  resources/quality/elegoo/base/pla040/pla_040028.inst.cfg
  resources/quality/elegoo/base/tpu040/tpu_040012.inst.cfg
  resources/quality/elegoo/base/tpu040/tpu_040016.inst.cfg
  resources/quality/elegoo/base/tpu040/tpu_040020.inst.cfg
  resources/quality/elegoo/base/tpu040/tpu_040024.inst.cfg
Labels: PR: Community Contribution :crown:

#14083 Add anycubic kobra go
  resources/definitions/anycubic_kobra_go.def.json
  resources/extruders/anycubic_kobra_go_extruder_0.def.json
  resources/quality/anycubic_kobra_go/anycubic_kobra_go_abs.inst.cfg
  resources/quality/anycubic_kobra_go/anycubic_kobra_go_pla.inst.cfg
  resources/quality/anycubic_kobra_go/anycubic_kobra_go_tpu.inst.cfg
Labels: PR: Printer Definitions :factory:, PR: Community Contribution :crown:

#14177 Add Voron Trident profiles, bed meshes, variants
  resources/definitions/voron_trident_250.def.json
  resources/definitions/voron_trident_300.def.json
  resources/definitions/voron_trident_350.def.json
  resources/definitions/voron_trident_base.def.json
  resources/meshes/voron_trident_250mm_bed_model.stl
  resources/meshes/voron_trident_300mm_bed_model.stl
  resources/meshes/voron_trident_350mm_bed_model.stl
  resources/variants/voron/voron_trident_250_0.40.inst.cfg
  resources/variants/voron/voron_trident_250_0.60.inst.cfg
  resources/variants/voron/voron_trident_250_0.80.inst.cfg
  resources/variants/voron/voron_trident_300_0.40.inst.cfg
  resources/variants/voron/voron_trident_300_0.60.inst.cfg
  resources/variants/voron/voron_trident_300_0.80.inst.cfg
  resources/variants/voron/voron_trident_350_0.40.inst.cfg
  resources/variants/voron/voron_trident_350_0.60.inst.cfg
  resources/variants/voron/voron_trident_350_0.80.inst.cfg
Labels: PR: Printer Definitions :factory:, PR: Community Contribution :crown:

#12134 Adding option: "Add prefix 'Printing'" to post processing plugin script "DisplayFilenameAndLayerOnLCD"
  plugins/PostProcessingPlugin/scripts/DisplayFilenameAndLayerOnLCD.py
Labels: PR: Community Contribution :crown:

#14339 [CURA-10167] - Fix Typo in Japanese mention of Extensions
  resources/i18n/ja_JP/cura.po
Labels: PR: Translations :books:
