Repository Ultimaker/Cura, pull requests merged in 2023-04, with the labels that each got.

#14272 Make Creality Ender 3 S1 consistent
  resources/definitions/creality_ender3s1.def.json
  resources/definitions/creality_ender3s1plus.def.json
  resources/definitions/creality_ender3s1pro.def.json
  resources/variants/creality/creality_ender3s1pro_0.2.inst.cfg
  resources/variants/creality/creality_ender3s1pro_0.3.inst.cfg
  resources/variants/creality/creality_ender3s1pro_0.5.inst.cfg
  resources/variants/creality/creality_ender3s1pro_0.6.inst.cfg
  resources/variants/creality/creality_ender3s1pro_0.8.inst.cfg
  resources/variants/creality/creality_ender3s1pro_1.0.inst.cfg
Labels: PR: Printer Definitions :factory:, PR: Community Contribution :crown:

#15022 Stop postprocessing plugin creating unnecessary script folders
  plugins/PostProcessingPlugin/PostProcessingPlugin.py
Labels: PR: Community Contribution :crown:

#15074 Suggested UI changes
  resources/definitions/Geeetech_Base_Dual_Extruder.def.json
  resources/definitions/Geeetech_Base_Multi_Extruder.def.json
  resources/definitions/Geeetech_Base_Single_Extruder.def.json
  resources/definitions/ankermake_m5.def.json
  resources/definitions/anycubic_i3_mega_s.def.json
  resources/definitions/artillery_base.def.json
  resources/definitions/biqu_base.def.json
  resources/definitions/blocks_base.def.json
  resources/definitions/creality_base.def.json
  resources/definitions/fdmprinter.def.json
  resources/definitions/flyingbear_base.def.json
  resources/definitions/fusion3_f410.def.json
  resources/definitions/kingroon_base.def.json
  resources/definitions/koonovo_base.def.json
  resources/definitions/koonovo_kn3.def.json
  resources/definitions/koonovo_kn5.def.json
  resources/definitions/lnl3d_base.def.json
  resources/definitions/longer_base.def.json
  resources/definitions/mingda_base.def.json
  resources/definitions/mixware_hyper_k.def.json
  resources/definitions/modix_v3_base.def.json
  resources/definitions/modix_v4_base.def.json
  resources/definitions/rigid3d_base.def.json
  resources/definitions/tank_m_base.def.json
  resources/definitions/tronxy_x.def.json
  resources/definitions/two_trees_base.def.json
  resources/definitions/vivedino_base.def.json
Labels: PR: Community Contribution :crown:

#15095 Adding two printers Tina2 and Tina2S
  resources/definitions/weedo_base.def.json
  resources/definitions/weefun_tina2.def.json
  resources/definitions/weefun_tina2s.def.json
  resources/extruders/weedo_base_extruder_0.def.json
Labels: PR: Printer Definitions :factory:, PR: Community Contribution :crown:

#15184 Add Kingroon KP3S Pro Printer
  resources/definitions/kingroon_kp3s_pro.def.json
Labels: PR: Community Contribution :crown:

#15015 Fix AppImage icons
  packaging/AppImage/create_appimage.py
  packaging/icons/cura-icon.svg
Labels: PR: Community Contribution :crown:

#15192 Add SV06 Plus profile
  resources/definitions/sovol_base.def.json
  resources/definitions/sovol_base_planetary.def.json
  resources/definitions/sovol_sv06.def.json
  resources/definitions/sovol_sv06_plus.def.json
  resources/variants/sovol/sovol_sv06_plus_0.2.inst.cfg
  resources/variants/sovol/sovol_sv06_plus_0.3.inst.cfg
  resources/variants/sovol/sovol_sv06_plus_0.4.inst.cfg
  resources/variants/sovol/sovol_sv06_plus_0.5.inst.cfg
  resources/variants/sovol/sovol_sv06_plus_0.6.inst.cfg
  resources/variants/sovol/sovol_sv06_plus_0.8.inst.cfg
  resources/variants/sovol/sovol_sv06_plus_1.0.inst.cfg
Labels: Status: Needs Info, PR: Community Contribution :crown:
