Repository Ultimaker/Cura, pull requests merged in 2023-10, with the labels that each got.

#11917 Fix thumbnail format
  plugins/PostProcessingPlugin/scripts/CreateThumbnail.py
Labels: PR: Community Contribution :crown:

#14928 Fix non-raw RegEx pattern string
  cura/UI/ObjectsModel.py
Labels: PR: Community Contribution :crown:

#15883 Update PostProcessingPlugin.py
  plugins/PostProcessingPlugin/PostProcessingPlugin.py
Labels: PR: Community Contribution :crown:

#16805 Update LimitXYAccelJerk
  plugins/PostProcessingPlugin/scripts/LimitXYAccelJerk.py
Labels: PR: Community Contribution :crown:

#16796 Add Creality Ender 3 V3 SE definition and nozzles
  resources/definitions/creality_ender3v3se.def.json
  resources/variants/creality/creality_ender3v3se_0.2.inst.cfg
  resources/variants/creality/creality_ender3v3se_0.3.inst.cfg
  resources/variants/creality/creality_ender3v3se_0.4.inst.cfg
  resources/variants/creality/creality_ender3v3se_0.5.inst.cfg
  resources/variants/creality/creality_ender3v3se_0.6.inst.cfg
  resources/variants/creality/creality_ender3v3se_0.8.inst.cfg
  resources/variants/creality/creality_ender3v3se_1.0.inst.cfg
Labels: PR: Printer Definitions :factory:, PR: Community Contribution :crown:

#16758 Fix spanish translation for lightning infill
  resources/i18n/es_ES/fdmprinter.def.json.po
Labels: PR: Translations :books:, PR: Community Contribution :crown:
