Repository Ultimaker/Cura, pull requests merged in 2024-02, with the labels that each got.

#17893 Allow to set print sequence manually
  conandata.yml
  cura/CuraApplication.py
  cura/HitChecker.py
  cura/OneAtATimeIterator.py
  cura/PrintOrderManager.py
  cura/Scene/CuraSceneNode.py
  cura/UI/ObjectsModel.py
  plugins/3MFReader/ThreeMFReader.py
  plugins/3MFWriter/ThreeMFWriter.py
  resources/definitions/fdmprinter.def.json
  resources/i18n/cs_CZ/cura.po
  resources/i18n/cs_CZ/fdmprinter.def.json.po
  resources/i18n/cura.pot
  resources/i18n/de_DE/cura.po
  resources/i18n/de_DE/fdmprinter.def.json.po
  resources/i18n/es_ES/cura.po
  resources/i18n/es_ES/fdmprinter.def.json.po
  resources/i18n/fdmprinter.def.json.pot
  resources/i18n/fi_FI/cura.po
  resources/i18n/fi_FI/fdmprinter.def.json.po
  resources/i18n/fr_FR/cura.po
  resources/i18n/fr_FR/fdmprinter.def.json.po
  resources/i18n/hu_HU/cura.po
  resources/i18n/hu_HU/fdmprinter.def.json.po
  resources/i18n/it_IT/cura.po
  resources/i18n/it_IT/fdmprinter.def.json.po
  resources/i18n/ja_JP/cura.po
  resources/i18n/ja_JP/fdmprinter.def.json.po
  resources/i18n/ko_KR/cura.po
  resources/i18n/ko_KR/fdmprinter.def.json.po
  resources/i18n/nl_NL/cura.po
  resources/i18n/nl_NL/fdmprinter.def.json.po
  resources/i18n/pl_PL/cura.po
  resources/i18n/pl_PL/fdmprinter.def.json.po
  resources/i18n/pt_BR/cura.po
  resources/i18n/pt_BR/fdmprinter.def.json.po
  resources/i18n/pt_PT/cura.po
  resources/i18n/pt_PT/fdmprinter.def.json.po
  resources/i18n/ru_RU/cura.po
  resources/i18n/ru_RU/fdmprinter.def.json.po
  resources/i18n/tr_TR/cura.po
  resources/i18n/tr_TR/fdmprinter.def.json.po
  resources/i18n/zh_CN/cura.po
  resources/i18n/zh_CN/fdmprinter.def.json.po
  resources/i18n/zh_TW/cura.po
  resources/i18n/zh_TW/fdmprinter.def.json.po
  resources/qml/Actions.qml
  resources/qml/Menus/ContextMenu.qml
  resources/qml/Menus/EditMenu.qml
  resources/setting_visibility/advanced.cfg
  resources/setting_visibility/expert.cfg
  tests/TestHitChecker.py
  tests/TestPrintOrderManager.py
Labels: PR: Community Contribution :crown:

#18372 restore extruder definition
  resources/extruders/geeetech_A20_1.def.json
Labels: PR: BooBoos :innocent:

#17053 Add navigation style option
  cura/CuraApplication.py
  resources/qml/Preferences/GeneralPage.qml
Labels: PR: Community Contribution :crown:, PR: Improving UI :art:
