Repository Ultimaker/Cura, pull requests merged in 2025-06, with the labels that each got.

#20693 Workflow fixes
  .github/workflows/printer-linter-pr-diagnose.yml
  .github/workflows/update-translation.yml
Labels: PR: Community Contribution :crown:, PR: BooBoos :innocent:, PR: Automation and build :robot:

#20660 Update PurgeLinesAndUnload.py
  plugins/PostProcessingPlugin/scripts/PurgeLinesAndUnload.py
Labels: PR: Community Contribution :crown:, PR: BooBoos :innocent:

#20444 InsertAtLayerChange: Make the conversion to uppercase optional
  plugins/PostProcessingPlugin/scripts/InsertAtLayerChange.py
Labels: PR: Community Contribution :crown:, PR: Post Processing :heavy_plus_sign:

#20694 Create slicing-error-check.yml
  .github/workflows/slicing-error-check.yml
Labels: PR: Community Contribution :crown:, PR: Automation and build :robot:

#20703 add Anycubic kobra 3 v2 (and ace pro) profiles
  resources/definitions/anycubic_kobra3v2.def.json
  resources/definitions/anycubic_kobra3v2_ACE_PRO.def.json
  resources/extruders/anycubic_kobra3v2_ACEPRO_extruder_0.def.json
  resources/extruders/anycubic_kobra3v2_ACEPRO_extruder_1.def.json
  resources/extruders/anycubic_kobra3v2_ACEPRO_extruder_2.def.json
  resources/extruders/anycubic_kobra3v2_ACEPRO_extruder_3.def.json
  resources/extruders/anycubic_kobra3v2_extruder_0.def.json
  resources/meshes/anycubic_kobra3v2_buildplate.stl
Labels: PR: Community Contribution :crown:
