Repository Ultimaker/Cura, pull requests merged in 2025-03, with the labels that each got.

#20339 Updated ja translation for 5.10
  resources/i18n/ja_JP/cura.po
  resources/i18n/ja_JP/fdmextruder.def.json.po
  resources/i18n/ja_JP/fdmprinter.def.json.po
Labels: PR: Community Contribution :crown:

#20386 Cura 12466 experimental setting visibility
  resources/qml/Preferences/SettingVisibilityItem.qml
  resources/qml/Preferences/SettingVisibilityPage.qml
Labels: PR: Improving UI :art:

#20368 Purgeline min z and fix
  plugins/PostProcessingPlugin/scripts/PurgeLinesAndUnload.py
Labels: PR: Community Contribution :crown:, PR: Post Processing :heavy_plus_sign:

#20437 Updated pt_BR strings for Cura
  resources/i18n/pt_BR/cura.po
  resources/i18n/pt_BR/fdmextruder.def.json.po
  resources/i18n/pt_BR/fdmprinter.def.json.po
Labels: PR: Community Contribution :crown:
